### ISSUE TITLE
Unable to connect from browser

### ISSUE THREAD

**Issue by corasaniti** [hectorm/docker-musikcube#1]
Hi,

orry for the question, but once I have launched the container why can't I connect via browser to the addresses

http: // my-ip: 7905
http: // my-ip: 7906

on port 7906 I get a denied permit while on 7906 I don't see anything
thank you

**Comment by corasaniti** [comment]
sorry if I ask you again but then I have to connect with the browser alla porta 7905 o 7906?
http: // my-ip: 7905
http: // my-ip: 7906
Thanks

**Comment by hectorm** [comment]
[musikcube](https://github.com/clangen/musikcube) is not a service that is accessed from a web browser. This Docker image is intended to deploy a streaming service and connect from musikdroid or another musikcube instance.
