### ISSUE TITLE
Is there a way to rescan the music directory without restarting the daemon?

### ISSUE THREAD

**Issue by gotbletu** [hectorm/docker-musikcube#3]
normally i have to use
`podman restart musikcube`

thanks for the container tho =)

**Comment by hectorm** [comment]
If you use the container as a client pressing `Ctrl`+`R` should bring up a dialog with this option and in the mobile app there is also an option to reload the library if you are connecting to the instance remotely.

**Comment by gotbletu** [comment]
ok thanks, i guess i can use the mobile app to do it
